package com.marco.player.main;

import com.marco.player.main.logic.logic;
import com.marco.player.main.ui.UI;
import com.sun.jna.NativeLibrary;
import uk.co.caprica.vlcj.binding.RuntimeUtil;
import uk.co.caprica.vlcj.media.MediaFactory;
import uk.co.caprica.vlcj.player.component.EmbeddedMediaPlayerComponent;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class player implements ActionListener {
    public JMenuBar menuBar;
    public JMenu media;
    public JPanel buttonPanel;
    public JButton playBnt;
    public JMenuItem openFile, quitApp;
    public JFrame mainFrame = new JFrame("Video Player");
    public EmbeddedMediaPlayerComponent component = new EmbeddedMediaPlayerComponent();
    public MediaFactory mediaFactory;
    UI ui = new UI(this);
    logic Logic = new logic(this);

    public player() {
        // Initialize the UI
        ui.UInit();
        // Initialize the UI setting
        ui.UIsetting();
        // Initialize the Menu
        ui.InitMenu();
        // Make the frame visible
        mainFrame.setVisible(true);
    }

    public static void main(String[] args) {
        new player();
        try {
            NativeLibrary.addSearchPath(RuntimeUtil.getLibVlcLibraryName(), "C:\\Program Files\\VideoLAN\\VLC");
        } catch (Error e) {
            System.out.println("Error in Line 32");
            //noinspection ThrowablePrintedToSystemOut
            System.out.println(e);
        }
        try {
            // set the file explore in window like (although I don't think it is look like windows' one)
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException classNotFoundException) {
            classNotFoundException.printStackTrace();
        }
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        String command = e.getActionCommand();

        switch (command) {
            case "open":
                JFileChooser fileChooser = new JFileChooser();
                Logic.openFile(fileChooser);
            case "quit":
                System.exit(0);
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        media = new JMenu();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.NORTH;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(media, gbc);
        buttonPanel = new JPanel();
        buttonPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.SOUTH;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(buttonPanel, gbc);
        playBnt = new JButton();
        playBnt.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.SOUTHWEST;
        buttonPanel.add(playBnt, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        buttonPanel.add(spacer1, gbc);
    }

}
